name: "CI"

on:
  push:
    branches: [ development ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ development ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [ 1.19.0 ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: Verify Formatting
      run: deno fmt --check

    - name: Run Linter
      run: deno lint

    - name: Module Loading Check
      run: deno run --reload ./mod.ts

    - name: Run tests
      run: deno test --allow-none
